version: '3'

services:
  face-recogniser-http:
    image: face-recogniser-http
    container_name: face-recogniser-service-http
    ports:
      - "8000:8000"
    volumes:
      - C:/images:/var/local
    entrypoint: ["uvicorn","http_service:app", "--host", "0.0.0.0", "--port", "8000"]
